### ISSUE TITLE
ตอนพยายามล็อกอินในส่งค่าคืนมาแบบนี้ครับ

### ISSUE THREAD

**Issue by gunnrcrakr** [maythiwat/TMNWallet#14]
`
{
"code":"50011",
"namespace":"TMN-PRODUCT",
"titleTh":"กรุณาอัปเดตแอปพลิเคชัน",
"titleEn":"System temporarily under maintenance",
"messageTh":"เพื่อความปลอดภัยและการใช้งานที่สมบูรณ์ กรุณาอัปเดตแอปเวอร์ชันล่าสุด",
"messageEn":"For system maintenance and better efficiency improvement, TrueMoney temporarily shut down the service. Sorry for your inconvenience.",
"originalMessage":"For system maintenance and better efficiency improvement, TrueMoney temporarily shut down the service. Sorry for your inconvenience.",
"developerMessage":"This error message is configured from Redis. Our system is not available at this time",
"data":{
}
}`

**Comment by maythiwat** [comment]
ย้ายไปใช้ตัวนี้แทนครับ
https://github.com/maythiwat/WalletAPI
